# Generated by Django 4.0.3 on 2022-03-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.TextField(verbose_name='Исходная строка')),
                ('prepared', models.JSONField(verbose_name='Заготовка')),
                ('count_variable', models.IntegerField(verbose_name='Количество переменных')),
            ],
        ),
    ]
