# Generated by Django 4.0.3 on 2022-03-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='lst_variable',
            field=models.JSONField(default=1, verbose_name='Список переменных'),
            preserve_default=False,
        ),
    ]
